name: ogg_opus_player_example
version: 1.0.0+1
publish_to: "none"
description: "Demonstrates how to use the ogg_opus_player plugin."

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  audio_session: ^0.2.2
  flutter:
    sdk: flutter
  ogg_record_player:
    path: ../
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  analysis_lints: ^1.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - audios/test.ogg
